# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jiemian.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 110, 741, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.guoyiButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.guoyiButton.setObjectName("guoyiButton")
        self.horizontalLayout.addWidget(self.guoyiButton)
        self.gdcwButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.gdcwButton.setObjectName("gdcwButton")
        self.horizontalLayout.addWidget(self.gdcwButton)
        self.gzcwButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.gzcwButton.setObjectName("gzcwButton")
        self.horizontalLayout.addWidget(self.gzcwButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 460, 741, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.filenameText = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.filenameText.setObjectName("filenameText")
        self.horizontalLayout_3.addWidget(self.filenameText)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(20, 510, 741, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.creatExcel = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.creatExcel.setObjectName("creatExcel")
        self.horizontalLayout_4.addWidget(self.creatExcel)
        self.leadtoOrcal = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.leadtoOrcal.setObjectName("leadtoOrcal")
        self.horizontalLayout_4.addWidget(self.leadtoOrcal)
        spacerItem2 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.Cancle = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.Cancle.setObjectName("Cancle")
        self.horizontalLayout_4.addWidget(self.Cancle)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 741, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Title = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Title.setObjectName("Title")
        self.verticalLayout.addWidget(self.Title, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 170, 741, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.zhaobiaoButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.zhaobiaoButton.setObjectName("zhaobiaoButton")
        self.horizontalLayout_2.addWidget(self.zhaobiaoButton)
        self.zhongbiaoButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.zhongbiaoButton.setObjectName("zhongbiaoButton")
        self.horizontalLayout_2.addWidget(self.zhongbiaoButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 220, 741, 101))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 1, 1, 1)
        self.biaotiText = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.biaotiText.setObjectName("biaotiText")
        self.gridLayout.addWidget(self.biaotiText, 1, 2, 1, 1)
        self.caigourenText = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.caigourenText.setObjectName("caigourenText")
        self.gridLayout.addWidget(self.caigourenText, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 2, 2, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 330, 741, 124))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.choosemessage = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.choosemessage.setObjectName("choosemessage")
        self.gridLayout_2.addWidget(self.choosemessage, 0, 0, 1, 1)
        self.P_buyer = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.P_buyer.setObjectName("P_buyer")
        self.gridLayout_2.addWidget(self.P_buyer, 4, 1, 1, 1)
        self.P_showtime = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.P_showtime.setObjectName("P_showtime")
        self.gridLayout_2.addWidget(self.P_showtime, 3, 1, 1, 1)
        self.P_title = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.P_title.setObjectName("P_title")
        self.gridLayout_2.addWidget(self.P_title, 1, 0, 1, 1)
        self.P_beginningtime = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.P_beginningtime.setObjectName("P_beginningtime")
        self.gridLayout_2.addWidget(self.P_beginningtime, 3, 0, 1, 1)
        self.P_agentCompany = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.P_agentCompany.setObjectName("P_agentCompany")
        self.gridLayout_2.addWidget(self.P_agentCompany, 4, 0, 1, 1)
        self.P_link = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.P_link.setObjectName("P_link")
        self.gridLayout_2.addWidget(self.P_link, 1, 1, 1, 1)
        self.P_account = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.P_account.setObjectName("P_account")
        self.gridLayout_2.addWidget(self.P_account, 2, 0, 1, 1)
        self.P_getaccount = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.P_getaccount.setObjectName("P_getaccount")
        self.gridLayout_2.addWidget(self.P_getaccount, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "选择网络："))
        self.guoyiButton.setText(_translate("MainWindow", "国义招标网"))
        self.gdcwButton.setText(_translate("MainWindow", "广东政府采购网"))
        self.gzcwButton.setText(_translate("MainWindow", "广州公共资源采购网"))
        self.label_3.setText(_translate("MainWindow", "Excel文件名："))
        self.creatExcel.setText(_translate("MainWindow", "生成Excel"))
        self.leadtoOrcal.setText(_translate("MainWindow", "导入数据库"))
        self.Cancle.setText(_translate("MainWindow", "取消"))
        self.Title.setText(_translate("MainWindow", "爬虫系统"))
        self.label_4.setText(_translate("MainWindow", "搜索类型："))
        self.zhaobiaoButton.setText(_translate("MainWindow", "招标公告"))
        self.zhongbiaoButton.setText(_translate("MainWindow", "中标公告"))
        self.label_5.setText(_translate("MainWindow", "搜索关键词"))
        self.label_6.setText(_translate("MainWindow", "采购人："))
        self.label_7.setText(_translate("MainWindow", "标题："))
        self.choosemessage.setText(_translate("MainWindow", "提取信息："))
        self.P_buyer.setText(_translate("MainWindow", "招标人"))
        self.P_showtime.setText(_translate("MainWindow", "开标时间"))
        self.P_title.setText(_translate("MainWindow", "招标标题"))
        self.P_beginningtime.setText(_translate("MainWindow", "发布时间"))
        self.P_agentCompany.setText(_translate("MainWindow", "代理机构"))
        self.P_link.setText(_translate("MainWindow", "招标链接"))
        self.P_account.setText(_translate("MainWindow", "招标预算"))
        self.P_getaccount.setText(_translate("MainWindow", "中标金额"))
